docs: Added link to clean air calculation pdf
MaibornWolff/clean-air pull request #68
Opened 2020-11-24 18:38 UTC by angrox

2020-11-25 06:00 UTC, thorsten requested changes

2020-11-25 06:00 UTC, thorsten commented on documentation/README.md
> +The effiency calculation can be found [here](theory.pdf).
May be we should add more here, e.g. 

`The effiency calculation of the device can be found [in this PDF document](theory.pdf).`

2020-11-26 21:31 UTC, mlkiefer approved these changes

2020-11-26 21:31 UTC, mlkiefer commented on README.md
> +We also have a [calculation (PDF)](documentation/theory.pdf) of the theoretical effiency of the clean air device.
```suggestion
We estimated the irradiance inside the device as described in the [calculation (PDF)](documentation/theory.pdf).
```

2020-11-26 21:31 UTC, mlkiefer commented on documentation/README.md
> +The effiency calculation can be found [here](theory.pdf).
```suggestion
Estimations about the irradiance and considerations about the room size for which such a device could be feasible are located [here](theory.pdf).
```

2020-11-26 21:39 UTC, mlkiefer submitted a review, later dismissed
I've added some suggestions

2020-12-17 07:27 UTC, thegreatdane6 approved these changes

2020-12-21 12:11 UTC, merged